# Generated by Django 4.0.5 on 2022-07-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_no_of_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='no_of_students',
        ),
        migrations.AddField(
            model_name='course',
            name='venue',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
