# Generated by Django 4.0.5 on 2022-07-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_timetable_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='session',
            field=models.CharField(default='', max_length=20),
        ),
    ]
