# Generated by Django 4.0.5 on 2022-07-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_timetable_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='session',
        ),
    ]
